from enum import Enum

class USERROLE(str, Enum):
    ADMIN = 'ADMIN'
    CUSTOMER = 'CUSTOMER'

class ORDERSTATUS(str, Enum):
    PENDING = 'PENDING'
    CONFIRMED = 'CONFIRMED'
    PREPARING = 'PREPARING'
    READY = 'READY'
    SERVED = 'SERVED'
    CANCELLED = 'CANCELLED'

class TABLESTATUS(str, Enum):
    AVALAIBLE = 'AVALAIBLE'
    OCCUPED = 'OCCUPED'
    RESERVED = 'RESERVED'
    UNAVAILABLE = 'UNAVAILABLE'

class RESERVATIONSTATUS(str, Enum):
    PENDING ='PENDING'
    CONFRIMED = 'CONFIRMED'
    CANCELLED = 'CANCELLED'
    COMPLETED = 'COMPLETED'

class PAYEMENTSTATUS(str, Enum):
    PENDING = 'PENDING'
    PAID = 'PAID'
    FAILED = 'FAILED'
    REFUNDED  = 'REFUNDED'

class PAYEMENTMETHOD(str, Enum):
    CASH = 'CASH'
    CARD = 'CARD'
    MOBILE_MONEY = 'MOBILE_MONEY'